### ISSUE TITLE
fix remote build of docs

### ISSUE THREAD

**Issue by drbenvincent** [pymc-labs/CausalPy#185]
Remote readthedocs failing with this error. Almost certainly due to the changes made in #184

```
Running Sphinx v6.2.1
making output directory... done
building [mo]: targets for 0 po files that are out of date
writing output... 
building [html]: targets for 8 source files that are out of date
updating environment: [new config] 8 added, 0 changed, 0 removed
reading sources... [ 12%] source/api_datasets
reading sources... [ 25%] source/api_plot_utils
reading sources... [ 37%] source/api_pymc_experiments
reading sources... [ 50%] source/api_pymc_models
reading sources... [ 62%] source/api_skl_experiments
reading sources... [ 75%] source/api_skl_models
reading sources... [ 87%] source/examples
reading sources... [100%] source/index

/home/docs/checkouts/readthedocs.org/user_builds/causalpy/checkouts/latest/docs/source/api_datasets.rst:7: ERROR: Unknown directive type "automodule".

.. automodule:: causalpy.data.datasets
   :members:
   :undoc-members:
/home/docs/checkouts/readthedocs.org/user_builds/causalpy/checkouts/latest/docs/source/api_plot_utils.rst:7: ERROR: Unknown directive type "automodule".

.. automodule:: causalpy.plot_utils
   :members:
   :undoc-members:
/home/docs/checkouts/readthedocs.org/user_builds/causalpy/checkouts/latest/docs/source/api_pymc_experiments.rst:7: ERROR: Unknown directive type "automodule".

.. automodule:: causalpy.pymc_experiments
   :members:
   :undoc-members:
   :inherited-members:
/home/docs/checkouts/readthedocs.org/user_builds/causalpy/checkouts/latest/docs/source/api_pymc_models.rst:7: ERROR: Unknown directive type "automodule".

.. automodule:: causalpy.pymc_models
   :members:
   :undoc-members:
/home/docs/checkouts/readthedocs.org/user_builds/causalpy/checkouts/latest/docs/source/api_skl_experiments.rst:7: ERROR: Unknown directive type "automodule".

.. automodule:: causalpy.skl_experiments
   :members:
   :undoc-members:
/home/docs/checkouts/readthedocs.org/user_builds/causalpy/checkouts/latest/docs/source/api_skl_models.rst:7: ERROR: Unknown directive type "automodule".

.. automodule:: causalpy.skl_models
   :members:
   :undoc-members:
/home/docs/checkouts/readthedocs.org/user_builds/causalpy/checkouts/latest/docs/source/examples.rst:4: WARNING: toctree contains reference to nonexisting document 'source/notebooks/ancova_pymc.ipynb'
/home/docs/checkouts/readthedocs.org/user_builds/causalpy/checkouts/latest/docs/source/examples.rst:13: WARNING: toctree contains reference to nonexisting document 'source/notebooks/sc_pymc.ipynb'
/home/docs/checkouts/readthedocs.org/user_builds/causalpy/checkouts/latest/docs/source/examples.rst:13: WARNING: toctree contains reference to nonexisting document 'source/notebooks/sc_skl.ipynb'
/home/docs/checkouts/readthedocs.org/user_builds/causalpy/checkouts/latest/docs/source/examples.rst:13: WARNING: toctree contains reference to nonexisting document 'source/notebooks/sc2_pymc.ipynb'
/home/docs/checkouts/readthedocs.org/user_builds/causalpy/checkouts/latest/docs/source/examples.rst:13: WARNING: toctree contains reference to nonexisting document 'source/notebooks/sc2_skl.ipynb'
/home/docs/checkouts/readthedocs.org/user_builds/causalpy/checkouts/latest/docs/source/examples.rst:13: WARNING: toctree contains reference to nonexisting document 'source/notebooks/sc_pymc_brexit.ipynb'
/home/docs/checkouts/readthedocs.org/user_builds/causalpy/checkouts/latest/docs/source/examples.rst:13: WARNING: toctree contains reference to nonexisting document 'source/notebooks/its_covid.ipynb'
/home/docs/checkouts/readthedocs.org/user_builds/causalpy/checkouts/latest/docs/source/examples.rst:13: WARNING: toctree contains reference to nonexisting document 'source/notebooks/geolift1.ipynb'
/home/docs/checkouts/readthedocs.org/user_builds/causalpy/checkouts/latest/docs/source/examples.rst:28: WARNING: toctree contains reference to nonexisting document 'source/notebooks/did_pymc.ipynb'
/home/docs/checkouts/readthedocs.org/user_builds/causalpy/checkouts/latest/docs/source/examples.rst:28: WARNING: toctree contains reference to nonexisting document 'source/notebooks/did_skl.ipynb'
/home/docs/checkouts/readthedocs.org/user_builds/causalpy/checkouts/latest/docs/source/examples.rst:28: WARNING: toctree contains reference to nonexisting document 'source/notebooks/did_pymc_banks.ipynb'
/home/docs/checkouts/readthedocs.org/user_builds/causalpy/checkouts/latest/docs/source/examples.rst:39: WARNING: toctree contains reference to nonexisting document 'source/notebooks/rd_pymc.ipynb'
/home/docs/checkouts/readthedocs.org/user_builds/causalpy/checkouts/latest/docs/source/examples.rst:39: WARNING: toctree contains reference to nonexisting document 'source/notebooks/rd_skl.ipynb'
/home/docs/checkouts/readthedocs.org/user_builds/causalpy/checkouts/latest/docs/source/examples.rst:39: WARNING: toctree contains reference to nonexisting document 'source/notebooks/rd_pymc_drinking.ipynb'
/home/docs/checkouts/readthedocs.org/user_builds/causalpy/checkouts/latest/docs/source/examples.rst:39: WARNING: toctree contains reference to nonexisting document 'source/notebooks/rd_skl_drinking.ipynb'
/home/docs/checkouts/readthedocs.org/user_builds/causalpy/checkouts/latest/docs/source/index.rst:120: WARNING: toctree contains reference to nonexisting document 'source/glossary.md'

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/causalpy/envs/latest/lib/python3.10/site-packages/sphinx/cmd/build.py", line 285, in build_main
    app.build(args.force_all, args.filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/causalpy/envs/latest/lib/python3.10/site-packages/sphinx/application.py", line 353, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/causalpy/envs/latest/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 311, in build_update
    self.build(to_build,
  File "/home/docs/checkouts/readthedocs.org/user_builds/causalpy/envs/latest/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 328, in build
    updated_docnames = set(self.read())
  File "/home/docs/checkouts/readthedocs.org/user_builds/causalpy/envs/latest/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 438, in read
    raise SphinxError('root file %s not found' %
sphinx.errors.SphinxError: root file /home/docs/checkouts/readthedocs.org/user_builds/causalpy/checkouts/latest/docs/index.rst not found

Sphinx error:
root file /home/docs/checkouts/readthedocs.org/user_builds/causalpy/checkouts/latest/docs/index.rst not found
```

**Comment by drbenvincent** [comment]
#186 did not fix the problem
