### ISSUE TITLE
Fix broken remote build of docs

### ISSUE THREAD

**Issue by drbenvincent** [pymc-labs/CausalPy#208]
The last PR (#207) seems to have broken just the remote build of the docs. Error from readthedocs:
```
Processing /home/docs/checkouts/readthedocs.org/user_builds/causalpy/checkouts/latest
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting arviz>=0.14.0 (from CausalPy==0.0.13)
  Downloading arviz-0.15.1-py3-none-any.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 110.4 MB/s eta 0:00:00
Collecting graphviz (from CausalPy==0.0.13)
  Downloading graphviz-0.20.1-py3-none-any.whl (47 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.0/47.0 kB 216.5 MB/s eta 0:00:00
Collecting ipython!=8.7.0 (from CausalPy==0.0.13)
  Downloading ipython-8.14.0-py3-none-any.whl (798 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 798.7/798.7 kB 210.4 MB/s eta 0:00:00
Collecting matplotlib>=3.5.3 (from CausalPy==0.0.13)
  Downloading matplotlib-3.7.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 149.1 MB/s eta 0:00:00
Collecting numpy (from CausalPy==0.0.13)
  Downloading numpy-1.24.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 55.4 MB/s eta 0:00:00
Collecting pandas (from CausalPy==0.0.13)
  Downloading pandas-2.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 229.2 MB/s eta 0:00:00
Collecting patsy (from CausalPy==0.0.13)
  Downloading patsy-0.5.3-py2.py3-none-any.whl (233 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.8/233.8 kB 278.8 MB/s eta 0:00:00
Collecting pymc>=5.0.0 (from CausalPy==0.0.13)
  Downloading pymc-5.5.0-py3-none-any.whl (448 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 448.4/448.4 kB 274.5 MB/s eta 0:00:00
Collecting scikit-learn>=1 (from CausalPy==0.0.13)
  Downloading scikit_learn-1.2.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.6/9.6 MB 184.8 MB/s eta 0:00:00
Collecting scipy (from CausalPy==0.0.13)
  Downloading scipy-1.10.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.4 MB)
     ━━━━━━━━━╸                               8.4/34.4 MB 174.4 MB/s eta 0:00:01
ERROR: Exception:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/causalpy/envs/latest/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/home/docs/checkouts/readthedocs.org/user_builds/causalpy/envs/latest/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "/home/docs/checkouts/readthedocs.org/user_builds/causalpy/envs/latest/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "/home/docs/.asdf/installs/python/3.10.8/lib/python3.10/http/client.py", line 465, in read
    s = self.fp.read(amt)
  File "/home/docs/.asdf/installs/python/3.10.8/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/home/docs/.asdf/installs/python/3.10.8/lib/python3.10/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/home/docs/.asdf/installs/python/3.10.8/lib/python3.10/ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/causalpy/envs/latest/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 169, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/causalpy/envs/latest/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/causalpy/envs/latest/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "/home/docs/checkouts/readthedocs.org/user_builds/causalpy/envs/latest/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/home/docs/checkouts/readthedocs.org/user_builds/causalpy/envs/latest/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/docs/checkouts/readthedocs.org/user_builds/causalpy/envs/latest/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 427, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/home/docs/checkouts/readthedocs.org/user_builds/causalpy/envs/latest/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 239, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "/home/docs/checkouts/readthedocs.org/user_builds/causalpy/envs/latest/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 230, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "/home/docs/checkouts/readthedocs.org/user_builds/causalpy/envs/latest/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "/home/docs/checkouts/readthedocs.org/user_builds/causalpy/envs/latest/lib/python3.10/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
    return bool(self._sequence)
  File "/home/docs/checkouts/readthedocs.org/user_builds/causalpy/envs/latest/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/home/docs/checkouts/readthedocs.org/user_builds/causalpy/envs/latest/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/home/docs/checkouts/readthedocs.org/user_builds/causalpy/envs/latest/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/home/docs/checkouts/readthedocs.org/user_builds/causalpy/envs/latest/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/home/docs/checkouts/readthedocs.org/user_builds/causalpy/envs/latest/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 293, in __init__
    super().__init__(
  File "/home/docs/checkouts/readthedocs.org/user_builds/causalpy/envs/latest/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "/home/docs/checkouts/readthedocs.org/user_builds/causalpy/envs/latest/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
  File "/home/docs/checkouts/readthedocs.org/user_builds/causalpy/envs/latest/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 304, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/home/docs/checkouts/readthedocs.org/user_builds/causalpy/envs/latest/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 516, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/home/docs/checkouts/readthedocs.org/user_builds/causalpy/envs/latest/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 587, in _prepare_linked_requirement
    local_file = unpack_url(
  File "/home/docs/checkouts/readthedocs.org/user_builds/causalpy/envs/latest/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 166, in unpack_url
    file = get_http_url(
  File "/home/docs/checkouts/readthedocs.org/user_builds/causalpy/envs/latest/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 107, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "/home/docs/checkouts/readthedocs.org/user_builds/causalpy/envs/latest/lib/python3.10/site-packages/pip/_internal/network/download.py", line 147, in __call__
    for chunk in chunks:
  File "/home/docs/checkouts/readthedocs.org/user_builds/causalpy/envs/latest/lib/python3.10/site-packages/pip/_internal/cli/progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "/home/docs/checkouts/readthedocs.org/user_builds/causalpy/envs/latest/lib/python3.10/site-packages/pip/_internal/network/utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "/home/docs/checkouts/readthedocs.org/user_builds/causalpy/envs/latest/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/docs/checkouts/readthedocs.org/user_builds/causalpy/envs/latest/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 560, in read
    with self._error_catcher():
  File "/home/docs/.asdf/installs/python/3.10.8/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/docs/checkouts/readthedocs.org/user_builds/causalpy/envs/latest/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
```

**Comment by drbenvincent** [comment]
False alarm. Was a readthedocs issue. Successfully build when manually triggered.
